

#' Synthetic mortality mortality for Australia
#'
#' A synthetic dataset of deaths and population
#' created by splitting out tabulations published
#' by the Australian Bureau of Statistics. The
#' splitting method is very simple, and does not produce
#' accurate rates or counts: the data should
#' *not* be used for estimating actual mortality
#' rates in Australia. The data should instead be
#' use for developing code that will ultimately
#' be used on real data, probably in
#' a secure environment.
#'
#' The starting point for the synthetic data is
#' the table "Deaths, Year of registration,
#' Indigenous status, Age at death, Sex, Five State/Territory"
#' in the [Data Explorer database](https://explore.data.abs.gov.au)
#' on the Australian Bureau of Statistics website.
#' The population counts and
#' age-specific mortality rates, which the ABS publishes
#' with broad age groups, are split into single
#' year of age, using splines. Synthetic death counts
#' are then generated by drawing from Poisson distributions.
#' The original data and the code to create the synthetic
#' data are included in the 'data-raw'
#' folder for this package.
#'
#' @format A data frame with 38,380 rows and the following columns:
#' - `age`: Single year of age, from 0 to 100.
#' - `sex`: `"Female"` or `"Male"`.
#' - `indig`: `"Indigenous"` or `"Non-Indigenous"`.
#' - `region`: `"New South Wales", "New South Wales",
#'   "Northern Territory", "Queensland", "South Australia",
#'   "Western Australia".
#' - `time`: Calendar year, 2003 to 2021.
#' - `deaths`: Count of deaths.
#' - `popn`: Count of population.
"synmort"
